### PR TITLE
Add honeypot spam protection to fix #113.

### LINKED ISSUE #113: The feedback form has no spam protection

### PR DESCRIPTION
**Pull request by michaelhagedon**
I'm tired of getting spam. :-)

### CODE REVIEW

**Comment by simpsonw** [comment]
@michaelhagedon, this looks good to me, but I'm having some trouble with the email functionality on my local build.  I will look at this as soon as I have that fixed.

**Comment by simpsonw** [comment]
@michaelhagedon The feedback mail functionality seems to be broken for me.  I've tried it both on webdev and my local build with no luck.  I checked the logs and saw

```
2015-02-11 11:04:09 Error: [SocketException] Invalid email: ""
Request URL: /applications/quickHelp/tutorials/provide_feedback/336
```
Are you still getting spam messages?

**Comment by michaelhagedon** [comment]
Are the email settings in config.yml filled out?

**Comment by simpsonw** [comment]
@michaelhagedon My local settings are:

```
email:
  # smtp (recommended) or php
  transport: smtp
  send_from: lbry-webadmin@email.arizona.edu
  send_all_feedback_to: wss.simpson@gmail.com 
  log: false
```

The webdev settings are:
```
email:
  send_from: webadmin@u.library.arizona.edu
  #send_all_feedback_to: hagedonm@u.library.arizona.edu
  send_all_feedback_to: wss.simpson@gmail.com 
```
I seem to be able to get the completion certificates without issue.

**Comment by michaelhagedon** [comment]
@simpsonw I won't know about spam until we put it in production. :-)

On this branch I was able to get mail on localhost sending through gmail.

**Comment by simpsonw** [comment]
@michaelhagedon I think I've figured out the problem.  The issue is that the feedback email will fail if the tutorial in question doesn't have a contact_email associated with it.  The behavior I was seeing didn't even give the user an error message; the form simply appeared to do nothing after you clicked submit.  The culprit is the call to addBcc on line 933 of the TutorialsController.  If you don't have a contact_email specified, it gets passed an empty string and then fails, but since it's outside of the try/catch block that send the success/failure message back to the browser, you don't have any idea what's going on.

Seeing as how this field is optional/nullable in the database, I think we should probably check to make sure it's not empty before sending the email.

**Comment by simpsonw** [comment]
Since the bug I was talking about previously doesn't really seem to have anything directly to do with this pull request, I've decided to make a separate issue (#115) to deal with it.  I will manually fixed the merge issue, review it, and commit/merge as appropriate.

**Comment by simpsonw** [comment]
FYI, this has been deployed to the UAL production server.

**Pull request merged**
